repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
    - id: ruff
      args: ["--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: debug-statements
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: trailing-whitespace

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
    - id: autopep8

  - repo: local
    hooks:
    - id: unittest
      name: unittest
      entry: python -c "import os, subprocess;
              os.chdir(subprocess.check_output(['git', 'rev-parse', '--show-toplevel']).strip().decode());
              import unittest; unittest.main(module='git_clone.tests.test_main', exit=True)"
      language: system
      pass_filenames: false
      stages: ["pre-commit"]
