repos:
  - repo: local
    hooks:
    - id: check-root-dir
      name: Check if commit is from repo root
      entry: bash -c 'test "$(pwd)" = "$(git rev-parse --show-toplevel)" || (echo "ERROR You must commit from the root of the repository!" && exit 1)'
      language: system
      stages: ["pre-commit"]
