repos:
  - repo: local
    hooks:
    - id: unittest
      name: unittest
      entry: python -m unittest
      language: system
      pass_filenames: false
      args: ["discover"]
      stages: ["pre-commit"]
    - id: check-root-dir
      name: Check if commit is from repo root
      entry: scripts/check-root-dir.sh
      language: system
      stages: ["pre-commit"]
