repos:
  - repo: local
    hooks:
    - id: unittest
      name: unittest
      entry: python -m unittest git_clone/tests/test_main.py
      language: system
      pass_filenames: false
      stages: ["pre-commit"]